### ISSUE TITLE
An error occurred when executing the command cmake --build . --config Release -j8.

### ISSUE THREAD

**Issue by LUORANCHENG** [chrxh/alien#107] opened 2024-10-17 11:03 UTC
The system information as follows:
    Operating System: Ubuntu 22.04
    CUDA Version: 12.4
    GCC Version: 11.4.0
    CMake Version: 3.22.1

error message:
```
[  0%] Building CXX object source/Base/CMakeFiles/Base.dir/Definitions.cpp.o
[  1%] Building CXX object external/ImFileDialog/CMakeFiles/im_file_dialog.dir/ImFileDialog.cpp.o
[  2%] Building CXX object source/Base/CMakeFiles/Base.dir/FileLogger.cpp.o
[  2%] Building CXX object source/Base/CMakeFiles/Base.dir/GlobalSettings.cpp.o
[  3%] Building CXX object source/Base/CMakeFiles/Base.dir/LoggingService.cpp.o
[  4%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/AuxiliaryDataParserService.cpp.o
[  4%] Building CXX object source/Base/CMakeFiles/Base.dir/Math.cpp.o
[  5%] Building CXX object source/Base/CMakeFiles/Base.dir/NumberGenerator.cpp.o
[  5%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/DataPointCollection.cpp.o
[  6%] Building CXX object source/Base/CMakeFiles/Base.dir/Physics.cpp.o
[  7%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/DescriptionEditService.cpp.o
[  7%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/Descriptions.cpp.o
[  7%] Building CXX object source/Base/CMakeFiles/Base.dir/StringHelper.cpp.o
[  8%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/Features.cpp.o
[  9%] Building CXX object source/Base/CMakeFiles/Base.dir/Vector2D.cpp.o
[ 10%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/GenomeDescriptionService.cpp.o
[ 10%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/LegacyAuxiliaryDataParserService.cpp.o
[ 11%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/PreviewDescriptionService.cpp.o
[ 11%] Building CXX object source/Base/CMakeFiles/Base.dir/VersionChecker.cpp.o
[ 11%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/SerializerService.cpp.o
[ 12%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/ShapeGenerator.cpp.o
[ 13%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/SimulationParameters.cpp.o
[ 13%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/SpaceCalculator.cpp.o
[ 14%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/StatisticsConverterService.cpp.o
[ 14%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/StatisticsHistory.cpp.o
[ 15%] Linking CXX static library libBase.a
[ 15%] Built target Base
[ 16%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkService.cpp.o
[ 16%] Building CXX object source/PersisterInterface/CMakeFiles/PersisterInterface.dir/TaskProcessor.cpp.o
[ 17%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkResourceParserService.cpp.o
[ 17%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkResourceRawTO.cpp.o
[ 18%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkResourceService.cpp.o
[ 19%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkResourceTreeTO.cpp.o
[ 19%] Building CXX object source/Network/CMakeFiles/Network.dir/ValidationService.cpp.o
[ 19%] Linking CXX static library libPersisterInterface.a
[ 19%] Built target PersisterInterface
[ 19%] Building CXX object source/PersisterImpl/CMakeFiles/PersisterImpl.dir/PersisterFacadeImpl.cpp.o
[ 20%] Building CXX object source/PersisterImpl/CMakeFiles/PersisterImpl.dir/PersisterRequestError.cpp.o
[ 20%] Building CXX object source/PersisterImpl/CMakeFiles/PersisterImpl.dir/PersisterWorker.cpp.o
[ 21%] Linking CXX static library libim_file_dialog.a
[ 21%] Built target im_file_dialog
[ 22%] Linking CXX static library libPersisterImpl.a
[ 22%] Built target PersisterImpl
[ 23%] Linking CXX static library libEngineInterface.a
[ 23%] Built target EngineInterface
[ 24%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/ConstantMemory.cu.o
[ 24%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/DataAccessKernels.cu.o
[ 25%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/DataAccessKernelsLauncher.cu.o
[ 25%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/DebugKernels.cu.o
[ 26%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/EditKernels.cu.o
[ 27%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/EditKernelsLauncher.cu.o
[ 27%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/FlowFieldKernels.cu.o
[ 28%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/GarbageCollectorKernels.cu.o
[ 28%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/GarbageCollectorKernelsLauncher.cu.o
[ 29%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/MaxAgeBalancer.cu.o
[ 30%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/Objects.cu.o
[ 30%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/RenderingData.cu.o
[ 31%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/RenderingKernels.cu.o
[ 31%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/RenderingKernelsLauncher.cu.o
[ 32%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/SimulationCudaFacade.cu.o
[ 33%] Linking CXX static library libNetwork.a
[ 33%] Built target Network
[ 34%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/SimulationData.cu.o
[ 34%] Building CXX object CMakeFiles/NetworkTests.dir/source/NetworkTests/NetworkResourceServiceTests.cpp.o
[ 35%] Building CXX object CMakeFiles/NetworkTests.dir/source/NetworkTests/Testsuite.cpp.o
[ 35%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/SimulationKernels.cu.o
[ 36%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/SimulationKernelsLauncher.cu.o
[ 36%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/StatisticsService.cu.o
[ 37%] Linking CXX executable NetworkTests
[ 37%] Built target NetworkTests
[ 38%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/StatisticsKernelsLauncher.cu.o
[ 39%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/StatisticsKernels.cu.o
[ 39%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/TestKernels.cu.o
[ 40%] Building CUDA object source/EngineGpuKernels/CMakeFiles/EngineGpuKernels.dir/TestKernelsLauncher.cu.o
[ 40%] Linking CUDA device code CMakeFiles/EngineGpuKernels.dir/cmake_device_link.o
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/librt.a' when searching for -lrt
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libpthread.a' when searching for -lpthread
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libdl.a' when searching for -ldl
[ 41%] Linking CXX static library libEngineGpuKernels.a
[ 41%] Built target EngineGpuKernels
[ 42%] Building CXX object source/EngineImpl/CMakeFiles/EngineImpl.dir/AccessDataTOCache.cpp.o
[ 42%] Building CXX object source/EngineImpl/CMakeFiles/EngineImpl.dir/DescriptionConverter.cpp.o
[ 43%] Building CXX object source/EngineImpl/CMakeFiles/EngineImpl.dir/EngineWorker.cpp.o
[ 43%] Building CXX object source/EngineImpl/CMakeFiles/EngineImpl.dir/SimulationFacadeImpl.cpp.o
[ 44%] Linking CXX static library libEngineImpl.a
[ 44%] Built target EngineImpl
[ 44%] Building CXX object CMakeFiles/cli.dir/source/Cli/Main.cpp.o
[ 45%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/AttackerTests.cpp.o
[ 45%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/CellConnectionTests.cpp.o
[ 46%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/ConstructorTests.cpp.o
[ 46%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/DataTransferTests.cpp.o
[ 48%] Building CXX object CMakeFiles/alien.dir/source/Gui/AboutDialog.cpp.o
[ 48%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/DefenderTests.cpp.o
[ 49%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/DescriptionHelperTests.cpp.o
[ 49%] Building CXX object CMakeFiles/alien.dir/source/Gui/ActivateUserDialog.cpp.o
[ 50%] Building CXX object CMakeFiles/alien.dir/source/Gui/AlienDialog.cpp.o
[ 51%] Building CXX object CMakeFiles/alien.dir/source/Gui/AlienImGui.cpp.o
[ 51%] Building CXX object CMakeFiles/alien.dir/source/Gui/AlienWindow.cpp.o
[ 51%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/DetonatorTests.cpp.o
[ 52%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/InjectorTests.cpp.o
[ 53%] Linking CUDA device code CMakeFiles/cli.dir/cmake_device_link.o
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libdl.a' when searching for -ldl
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/librt.a' when searching for -lrt
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libpthread.a' when searching for -lpthread
[ 53%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/IntegrationTestFramework.cpp.o
[ 53%] Linking CXX executable cli
/usr/bin/ld: source/EngineGpuKernels/libEngineGpuKernels.a(cmake_device_link.o): in function `__cudaRegisterLinkedBinary_84dd3936_22_cuda_device_runtime_cu_8b1a5d37':
/usr/lib/nvidia-cuda-toolkit/bin/crt/link.stub:141: undefined reference to `__fatbinwrap_84dd3936_22_cuda_device_runtime_cu_8b1a5d37'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/cli.dir/build.make:175：cli] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:340：CMakeFiles/cli.dir/all] 错误 2
gmake[1]: *** 正在等待未完成的任务....
[ 54%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/LivingStateTransitionTests.cpp.o
[ 55%] Building CXX object CMakeFiles/alien.dir/source/Gui/AutosaveController.cpp.o
[ 55%] Building CXX object CMakeFiles/alien.dir/source/Gui/AutosaveWindow.cpp.o
[ 56%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/MuscleTests.cpp.o
[ 56%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/MutationTests.cpp.o
[ 57%] Building CXX object CMakeFiles/alien.dir/source/Gui/BrowserWindow.cpp.o
[ 58%] Building CXX object CMakeFiles/alien.dir/source/Gui/ChangeColorDialog.cpp.o
[ 58%] Building CXX object CMakeFiles/alien.dir/source/Gui/CreateUserDialog.cpp.o
[ 59%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/NerveTests.cpp.o
[ 60%] Building CXX object CMakeFiles/alien.dir/source/Gui/CreatorWindow.cpp.o
[ 60%] Building CXX object CMakeFiles/alien.dir/source/Gui/DelayedExecutionController.cpp.o
[ 60%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/NeuronTests.cpp.o
[ 61%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/ReconnectorTests.cpp.o
[ 62%] Building CXX object CMakeFiles/alien.dir/source/Gui/DeleteUserDialog.cpp.o
[ 63%] Building CXX object CMakeFiles/alien.dir/source/Gui/DisplaySettingsDialog.cpp.o
[ 64%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/SensorTests.cpp.o
[ 64%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/StatisticsTests.cpp.o
[ 64%] Building CXX object CMakeFiles/alien.dir/source/Gui/EditorController.cpp.o
[ 65%] Building CXX object CMakeFiles/alien.dir/source/Gui/EditorModel.cpp.o
[ 65%] Building CXX object CMakeFiles/alien.dir/source/Gui/EditSimulationDialog.cpp.o
[ 66%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/Testsuite.cpp.o
[ 67%] Building CXX object CMakeFiles/alien.dir/source/Gui/ExitDialog.cpp.o
[ 68%] Building CXX object CMakeFiles/alien.dir/source/Gui/FileTransferController.cpp.o
[ 68%] Building CXX object CMakeFiles/alien.dir/source/Gui/FpsController.cpp.o
[ 68%] Building CXX object CMakeFiles/EngineTests.dir/source/EngineTests/TransmitterTests.cpp.o
[ 69%] Building CXX object CMakeFiles/alien.dir/source/Gui/GenericFileDialogs.cpp.o
[ 69%] Building CXX object CMakeFiles/alien.dir/source/Gui/GenomeEditorWindow.cpp.o
[ 70%] Building CXX object CMakeFiles/alien.dir/source/Gui/GettingStartedWindow.cpp.o
[ 71%] Building CXX object CMakeFiles/alien.dir/source/Gui/GpuSettingsDialog.cpp.o
[ 71%] Building CXX object CMakeFiles/alien.dir/source/Gui/GuiLogger.cpp.o
[ 72%] Building CXX object CMakeFiles/alien.dir/source/Gui/HistogramLiveStatistics.cpp.o
[ 72%] Building CXX object CMakeFiles/alien.dir/source/Gui/ImageToPatternDialog.cpp.o
[ 73%] Building CXX object CMakeFiles/alien.dir/source/Gui/InspectorWindow.cpp.o
[ 74%] Building CXX object CMakeFiles/alien.dir/source/Gui/LastSessionBrowserData.cpp.o
[ 74%] Building CXX object CMakeFiles/alien.dir/source/Gui/LoginController.cpp.o
[ 75%] Building CXX object CMakeFiles/alien.dir/source/Gui/LoginDialog.cpp.o
[ 75%] Building CXX object CMakeFiles/alien.dir/source/Gui/LogWindow.cpp.o
[ 76%] Building CXX object CMakeFiles/alien.dir/source/Gui/Main.cpp.o
[ 77%] Building CXX object CMakeFiles/alien.dir/source/Gui/MainWindow.cpp.o
[ 77%] Building CXX object CMakeFiles/alien.dir/source/Gui/MassOperationsDialog.cpp.o
[ 78%] Building CXX object CMakeFiles/alien.dir/source/Gui/MessageDialog.cpp.o
[ 79%] Linking CUDA device code CMakeFiles/EngineTests.dir/cmake_device_link.o
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libdl.a' when searching for -ldl
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/librt.a' when searching for -lrt
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libpthread.a' when searching for -lpthread
[ 79%] Building CXX object CMakeFiles/alien.dir/source/Gui/MultiplierWindow.cpp.o
[ 80%] Linking CXX executable EngineTests
/usr/bin/ld: source/EngineInterface/libEngineInterface.a(SerializerService.cpp.o): in function `SerializerService::deserializeDataDescription(ClusteredDataDescription&, std::istream&)':
SerializerService.cpp:(.text+0x9b52): undefined reference to `VersionChecker::isVersionValid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: SerializerService.cpp:(.text+0x9b62): undefined reference to `VersionChecker::isVersionOutdated(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: source/EngineGpuKernels/libEngineGpuKernels.a(cmake_device_link.o): in function `__cudaRegisterLinkedBinary_84dd3936_22_cuda_device_runtime_cu_8b1a5d37':
/usr/lib/nvidia-cuda-toolkit/bin/crt/link.stub:141: undefined reference to `__fatbinwrap_84dd3936_22_cuda_device_runtime_cu_8b1a5d37'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/EngineTests.dir/build.make:493：EngineTests] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:369：CMakeFiles/EngineTests.dir/all] 错误 2
[ 81%] Building CXX object CMakeFiles/alien.dir/source/Gui/NetworkSettingsDialog.cpp.o
[ 82%] Building CXX object CMakeFiles/alien.dir/source/Gui/NetworkTransferController.cpp.o
[ 82%] Building CXX object CMakeFiles/alien.dir/source/Gui/NewSimulationDialog.cpp.o
[ 83%] Building CXX object CMakeFiles/alien.dir/source/Gui/NewPasswordDialog.cpp.o
[ 83%] Building CXX object CMakeFiles/alien.dir/source/Gui/OpenGLHelper.cpp.o
[ 84%] Building CXX object CMakeFiles/alien.dir/source/Gui/OverlayMessageController.cpp.o
[ 85%] Building CXX object CMakeFiles/alien.dir/source/Gui/PatternAnalysisDialog.cpp.o
[ 85%] Building CXX object CMakeFiles/alien.dir/source/Gui/PatternEditorWindow.cpp.o
[ 86%] Building CXX object CMakeFiles/alien.dir/source/Gui/RadiationSourcesWindow.cpp.o
[ 86%] Building CXX object CMakeFiles/alien.dir/source/Gui/ResetPasswordDialog.cpp.o
[ 87%] Building CXX object CMakeFiles/alien.dir/source/Gui/ResizeWorldDialog.cpp.o
[ 88%] Building CXX object CMakeFiles/alien.dir/source/Gui/SelectionWindow.cpp.o
[ 88%] Building CXX object CMakeFiles/alien.dir/source/Gui/Shader.cpp.o
[ 89%] Building CXX object CMakeFiles/alien.dir/source/Gui/ShaderWindow.cpp.o
[ 89%] Building CXX object CMakeFiles/alien.dir/source/Gui/SerializationHelperService.cpp.o
[ 90%] Building CXX object CMakeFiles/alien.dir/source/Gui/SimulationInteractionController.cpp.o
[ 91%] Building CXX object CMakeFiles/alien.dir/source/Gui/SimulationParametersWindow.cpp.o
[ 91%] Building CXX object CMakeFiles/alien.dir/source/Gui/SimulationScrollbar.cpp.o
[ 92%] Building CXX object CMakeFiles/alien.dir/source/Gui/SimulationView.cpp.o
[ 92%] Building CXX object CMakeFiles/alien.dir/source/Gui/SpatialControlWindow.cpp.o
[ 93%] Building CXX object CMakeFiles/alien.dir/source/Gui/StartupController.cpp.o
[ 94%] Building CXX object CMakeFiles/alien.dir/source/Gui/StatisticsWindow.cpp.o
[ 94%] Building CXX object CMakeFiles/alien.dir/source/Gui/StyleRepository.cpp.o
[ 95%] Building CXX object CMakeFiles/alien.dir/source/Gui/TableLiveStatistics.cpp.o
[ 95%] Building CXX object CMakeFiles/alien.dir/source/Gui/TemporalControlWindow.cpp.o
[ 96%] Building CXX object CMakeFiles/alien.dir/source/Gui/TimelineLiveStatistics.cpp.o
[ 97%] Building CXX object CMakeFiles/alien.dir/source/Gui/UiController.cpp.o
[ 97%] Building CXX object CMakeFiles/alien.dir/source/Gui/UploadSimulationDialog.cpp.o
[ 98%] Building CXX object CMakeFiles/alien.dir/source/Gui/Viewport.cpp.o
[ 98%] Building CXX object CMakeFiles/alien.dir/source/Gui/WindowController.cpp.o
[ 99%] Linking CUDA device code CMakeFiles/alien.dir/cmake_device_link.o
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libdl.a' when searching for -ldl
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/librt.a' when searching for -lrt
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libpthread.a' when searching for -lpthread
[100%] Linking CXX executable alien
/usr/bin/ld: source/EngineGpuKernels/libEngineGpuKernels.a(cmake_device_link.o): in function `__cudaRegisterLinkedBinary_84dd3936_22_cuda_device_runtime_cu_8b1a5d37':
/usr/lib/nvidia-cuda-toolkit/bin/crt/link.stub:141: undefined reference to `__fatbinwrap_84dd3936_22_cuda_device_runtime_cu_8b1a5d37'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/alien.dir/build.make:1383：alien] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:311：CMakeFiles/alien.dir/all] 错误 2
gmake: *** [Makefile:91：all] 错误 2
```

I really like your project, and I hope I can get it running.
thanks🌹🌹🌹

**Comment by Gardene-el** [comment] 2024-10-17 16:40
Maybe you could update your GCC and CUDA version first, since I'm not sure if 
```
/usr/bin/ld: source/EngineInterface/libEngineInterface.a(SerializerService.cpp.o): in function `SerializerService::deserializeDataDescription(ClusteredDataDescription&, std::istream&)':
SerializerService.cpp:(.text+0x9b52): undefined reference to `VersionChecker::isVersionValid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: SerializerService.cpp:(.text+0x9b62): undefined reference to `VersionChecker::isVersionOutdated(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: source/EngineGpuKernels/libEngineGpuKernels.a(cmake_device_link.o): in function `__cudaRegisterLinkedBinary_84dd3936_22_cuda_device_runtime_cu_8b1a5d37':
/usr/lib/nvidia-cuda-toolkit/bin/crt/link.stub:141: undefined reference to `__fatbinwrap_84dd3936_22_cuda_device_runtime_cu_8b1a5d37'
collect2: error: ld returned 1 exit status
```
this part is caused by GCC 11.4.0 incompatiblity.

**Comment by chrxh** [comment] 2024-10-17 19:35
The linker error regarding the VersionChecker should be fixed in the latest commit (there was a missing dependency in the CMakeLists, where some GCC version care about that and others not).
Regarding the CUDA error, I agree with @Gardene-el: Please try to update to the latest CUDA Toolkit (v12.6).

**Comment by LUORANCHENG** [comment] 2024-10-18 03:11
When I use CUDA 12.6 and GCC 12.3.0, I encountered a new error:
```
[  0%] Building CXX object source/Base/CMakeFiles/Base.dir/Definitions.cpp.o
[  1%] Building CXX object external/ImFileDialog/CMakeFiles/im_file_dialog.dir/ImFileDialog.cpp.o
[  2%] Building CXX object source/Base/CMakeFiles/Base.dir/FileLogger.cpp.o
[  2%] Building CXX object source/Base/CMakeFiles/Base.dir/GlobalSettings.cpp.o
[  3%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/AuxiliaryDataParserService.cpp.o
[  4%] Building CXX object source/Base/CMakeFiles/Base.dir/LoggingService.cpp.o
[  4%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/DataPointCollection.cpp.o
[  4%] Building CXX object source/Base/CMakeFiles/Base.dir/Math.cpp.o
[  5%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/DescriptionEditService.cpp.o
[  5%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/Descriptions.cpp.o
[  6%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/Features.cpp.o
[  7%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/GenomeDescriptionService.cpp.o
[  7%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/LegacyAuxiliaryDataParserService.cpp.o
[  8%] Building CXX object source/Base/CMakeFiles/Base.dir/NumberGenerator.cpp.o
[  9%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/PreviewDescriptionService.cpp.o
[ 10%] Building CXX object source/Base/CMakeFiles/Base.dir/Physics.cpp.o
[ 10%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/SerializerService.cpp.o
[ 10%] Building CXX object source/Base/CMakeFiles/Base.dir/StringHelper.cpp.o
[ 11%] Building CXX object source/Base/CMakeFiles/Base.dir/Vector2D.cpp.o
In file included from /usr/include/c++/12/array:43,
                 from /home/ihavc/other_project/alien/source/Base/Definitions.h:3,
                 from /home/ihavc/other_project/alien/source/EngineInterface/DescriptionEditService.h:3,
                 from /home/ihavc/other_project/alien/source/EngineInterface/DescriptionEditService.cpp:1:
In function ‘constexpr decltype (__comp((* __first1), (* __first2))) std::lexicographical_compare_three_way(_InputIter1, _InputIter1, _InputIter2, _InputIter2, _Comp) [with _InputIter1 = __gnu_cxx::__normal_iterator<const unsigned char*, vector<unsigned char> >; _InputIter2 = __gnu_cxx::__normal_iterator<const unsigned char*, vector<unsigned char> >; _Comp = __detail::_Synth3way]’,
    inlined from ‘constexpr std::__detail::__synth3way_t<_T1> std::operator<=>(const vector<_Tp, _Alloc>&, const vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = allocator<unsigned char>]’ at /usr/include/c++/12/bits/stl_vector.h:2056:52,
    inlined from ‘constexpr bool std::less<_Tp>::operator()(const _Tp&, const _Tp&) const [with _Tp = std::vector<unsigned char>]’ at /usr/include/c++/12/bits/stl_function.h:408:20,
    inlined from ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_unique_pos(const key_type&) [with _Key = std::vector<unsigned char>; _Val = std::pair<const std::vector<unsigned char>, long unsigned int>; _KeyOfValue = std::_Select1st<std::pair<const std::vector<unsigned char>, long unsigned int> >; _Compare = std::less<std::vector<unsigned char> >; _Alloc = std::allocator<std::pair<const std::vector<unsigned char>, long unsigned int> >]’ at /usr/include/c++/12/bits/stl_tree.h:2119:35:
/usr/include/c++/12/bits/stl_algobase.h:1843:41: error: ‘int __builtin_memcmp(const void*, const void*, long unsigned int)’ specified bound [9223372036854775808, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Werror=stringop-overread]
 1843 |                       = __builtin_memcmp(&*__first1, &*__first2, __len) <=> 0;
      |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 11%] Building CXX object source/Base/CMakeFiles/Base.dir/VersionChecker.cpp.o
[ 12%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/ShapeGenerator.cpp.o
[ 13%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/SimulationParameters.cpp.o
[ 13%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/SpaceCalculator.cpp.o
[ 14%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/StatisticsConverterService.cpp.o
[ 14%] Building CXX object source/EngineInterface/CMakeFiles/EngineInterface.dir/StatisticsHistory.cpp.o
cc1plus: all warnings being treated as errors
gmake[2]: *** [source/EngineInterface/CMakeFiles/EngineInterface.dir/build.make:104：source/EngineInterface/CMakeFiles/EngineInterface.dir/DescriptionEditService.cpp.o] 错误 1
gmake[2]: *** 正在等待未完成的任务....
[ 15%] Linking CXX static library libBase.a
[ 15%] Built target Base
[ 16%] Building CXX object source/PersisterInterface/CMakeFiles/PersisterInterface.dir/TaskProcessor.cpp.o
[ 16%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkService.cpp.o
[ 17%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkResourceParserService.cpp.o
[ 17%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkResourceRawTO.cpp.o
[ 18%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkResourceService.cpp.o
[ 19%] Building CXX object source/Network/CMakeFiles/Network.dir/NetworkResourceTreeTO.cpp.o
[ 19%] Building CXX object source/Network/CMakeFiles/Network.dir/ValidationService.cpp.o
[ 19%] Linking CXX static library libPersisterInterface.a
[ 19%] Built target PersisterInterface
[ 19%] Building CXX object source/PersisterImpl/CMakeFiles/PersisterImpl.dir/PersisterFacadeImpl.cpp.o
[ 19%] Building CXX object source/PersisterImpl/CMakeFiles/PersisterImpl.dir/PersisterWorker.cpp.o
[ 20%] Building CXX object source/PersisterImpl/CMakeFiles/PersisterImpl.dir/PersisterRequestError.cpp.o
[ 21%] Linking CXX static library libim_file_dialog.a
[ 21%] Built target im_file_dialog
[ 22%] Linking CXX static library libPersisterImpl.a
[ 22%] Built target PersisterImpl
gmake[1]: *** [CMakeFiles/Makefile2:530：source/EngineInterface/CMakeFiles/EngineInterface.dir/all] 错误 2
gmake[1]: *** 正在等待未完成的任务....
[ 23%] Linking CXX static library libNetwork.a
[ 23%] Built target Network
gmake: *** [Makefile:91：all] 错误 2
```

**Comment by LUORANCHENG** [comment] 2024-10-18 03:39
When I cloned the repository again and compiled it with CUDA 12.6 and gcc 11.4.0, it ran successfully. Thanks everyone!🌹🌹🌹

**Closed** 2024-10-18 03:39 UTC
